#!/bin/bash
#####################################################
# Author          : yunxing - yunxing.cyx
# Last modified   : 2011-12-28 16:53
# Function        : show qps of webserver 
# Usage           : 
#                    check_qps [-h] [LOGPATH]
#                    LOGPATH : the accesslog path we read 
#####################################################

LANG=C

if [ $# -ge 1 ] 
then
	if [ "x$1" = "x-h" ]
	then
		echo "-qps  [logfile-path]"
		exit 0
	fi
	acc_logs=$1
else
	acc_logs=/home/admin/cai/logs/cronolog/`date +%Y/%m/%Y-%m-%d-`taobao-access_log
	
fi

function getQPS_RT(){
	if [ -f $acc_logs ]
	then
		srm=" [`date -d ' -1 second '  +%d/%h/%Y:%H:%M:%S` +0800] "
		QPS=`grep -c -F  "$srm" $acc_logs`
	else
		QPS='[NOLOG]'
	fi
}


# -------------- Main -------------- #


getQPS_RT

# ------------ rsult -------------- #

echo $QPS



