#!/bin/bash
#appname=`ps -ef | awk '$0 ~ /java/{for(i=1;i<=NF;i++){if($i ~ /-Djboss\.server\.home\.dir=/ || $i ~ /-Djetty\.home/){split($i,array,"/");print array[4];exit}}}'`
appname=`ps -ef | awk '$0 ~ /java/{for(i=1;i<=NF;i++){if($i ~ /\/home\/admin\/.*\/\.default/){split($i,array,"/");print array[4];exit}}}'`
if [ -n "$appname" ];then
    apppath="/home/admin/$appname";
    find_dir="$apppath/target/taobao-hsf.sar/lib/"
    if [ -e "$find_dir" ];then
        result=`ls $find_dir | awk -F'-' '$1 ~ /^hsf\.container$/{content=$2;for(i=3;i<=NR;i++)content=content"-"$i;print substr(content,1,index(content,".jar")-1);exit}'`
        if [ -n "$result" ];then
            echo "[$result]";
        else
            echo "[null]"
        fi
    else
        echo "[null]"
    fi
else
    echo "[null]"
fi

