#!/bin/bash
#####################################################
# Author          : yunxing - yunxing.cyx
# Last modified   : 2011-12-28 16:53
# Function        : show mem free info in bytes
# Usage           : 
#                    check_mem [-h] 
#####################################################

LANG=C

if [ "x$1" = "x-h" ]
then
	echo "mem "
	exit 0
fi

free -b | grep -- -/+ | awk '{print $4}'
