#!/bin/bash
appname=`ps -ef | awk '$0 ~ /java/{for(i=1;i<=NF;i++){if($i ~ /\/home\/admin\/.*\/\.default/){split($i,array,"/");print array[4];exit}}}'`
if [ -n "$appname" ];then
    apppath="/home/admin/$appname"
    find_dir="$apppath/target/$appname.war/WEB-INF/lib/"
    if [ -e "$find_dir" ];then
#        result=`ls $find_dir | awk -F'-' '$1 ~ /^notify$/ && $3 ~ /\<client\>/{content=$4;for(i=5;i<=NR;i++)content=content"-"$i;print substr(content,1,index(content,".jar")-1);exit}'`
        result=`ls $find_dir | awk -F'-' '$1 ~ /^notify$/ && $3 ~ /\<client\>/ {print substr($NF,1,index($NF,".jar")-1);exit}'`
        if [ -n "$result" ];then
            echo "[$result]";
        else
            echo "[null]";
        fi
    else
        echo "[null]"
    fi
else
    echo "[null]"
fi

