#!/bin/bash
appname=`ps -ef | awk '$0 ~ /java/{for(i=1;i<=NF;i++){if($i ~ /\/home\/admin\/.*\/\.default/){split($i,array,"/");print array[4];exit}}}'`
if [ -n "$appname" ];then
    apppath="/home/admin/$appname";
    find_dir="$apppath/target/$appname.war/WEB-INF/lib/"
    if [ -e "$find_dir" ];then
        result=`ls $find_dir | grep tbsession|awk -F- '{print $2}'|awk -F.j '{print $1}'`
        if [ -n "$result" ];then
            echo "[$result]";
        else
            echo "[null]"
        fi
    else
        echo "[null]"
    fi
else
    echo "[null]"
fi
