#!/bin/bash
#appname=`ps -ef | awk '$0 ~ /java/{for(i=1;i<=NF;i++){if($i ~ /-Djboss\.server\.home\.dir=/ || $i ~ /-Djetty\.home/){split($i,array,"/");print array[4];exit}}}'`
appname=`ps -ef | awk '$0 ~ /java/{for(i=1;i<=NF;i++){if($i ~ /\/home\/admin\/.*\/\.default/){split($i,array,"/");print array[4];exit}}}'`
if [ -n "$appname" ];then
    apppath="/home/admin/$appname";
    filepath="$apppath/target/$appname.war/WEB-INF/log4j.xml"
    if [ -e "$filepath" ];then
        result=`egrep "<.*name[[:blank:]]*=[[:blank:]]*\".*\"[[:blank:]]*value=[[:blank:]]*\"(\<info\>|\<debug\>)\"[[:blank:]]*/>" "$filepath"`
       
        if [ -n "$result" ];then
        then
            if expr match $result "<info>" &>/dev/null
               echo "[info]"
            else
               echo "[debug]"
            fi
        else
            echo "[null]"
        fi
    else
        echo "[null]"
    fi
else
    echo "[null]"
fi

